### PR TITLE
version bumps, then add JDK 11 and 17 to CI matrix

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
looks like Travis-CI isn't working, so I don't know if this is actually mergeable

I don't necessarily have an interest in getting this merged. the motivation here is simply to inform you that macwire's tests fail on JDK 17, because of https://openjdk.java.net/jeps/403, as seen at https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/15/artifact/logs/macwire-build.log

**Comment by adamw** [comment]
Thanks! I'll take the occasion to modernize the build & move it to GH Actions. I think it should support jdk 17 builds as well, at least I'll try to add them :)

**Comment by adamw** [comment]
Hm no, the latest available on GH actions (at least using setup-java) is 16. Anyway, I've opened https://github.com/softwaremill/macwire/issues/163 to investigate & fix this further.

**Comment by SethTisue** [comment]
> Hm no, the latest available on GH actions (at least using setup-java) is 16

try `17-ea` (instead of just plain `17`)

**Comment by adamw** [comment]
Ha, I think this worked. Thanks! :)

**Pull request merged**
